@extends('layouts.admin')

@section('content')
<div class="container mt-4">
    <h2 class="mb-4 fw-bold">Referral Code Details</h2>

    <div class="row">
        <div class="col-md-8">
            <div class="card shadow-sm border-0">
                <div class="card-header bg-white">
                    <h6 class="mb-0">Code Information</h6>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Code:</strong> {{ $code->code }}</p>
                            <p><strong>Status:</strong>
                                <span class="badge bg-{{ $code->status === 'used' ? 'success' : ($code->status === 'expired' ? 'danger' : 'warning') }}">
                                    {{ ucfirst($code->status) }}
                                </span>
                            </p>
                            <p><strong>Generated By:</strong> {{ $code->generatedBy->name ?? 'N/A' }}</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>Assigned To:</strong> {{ $code->assignedTo->name ?? 'N/A' }}</p>
                            <p><strong>Used By:</strong> {{ $code->usedBy->name ?? 'N/A' }}</p>
                            <p><strong>Expires At:</strong> {{ $code->expires_at ? $code->expires_at->format('Y-m-d H:i') : 'N/A' }}</p>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-12">
                            <p><strong>Created At:</strong> {{ $code->created_at->format('Y-m-d H:i') }}</p>
                            <p><strong>Updated At:</strong> {{ $code->updated_at->format('Y-m-d H:i') }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow-sm border-0">
                <div class="card-header bg-white">
                    <h6 class="mb-0">Actions</h6>
                </div>
                <div class="card-body">
                    <a href="{{ route('admin.referral_codes.index') }}" class="btn btn-secondary w-100 mb-2">
                        <i class="bi bi-arrow-left me-2"></i>Back to List
                    </a>
                    @if($code->status === 'available')
                        <form action="{{ route('admin.referral_codes.assign', $code) }}" method="POST" class="mb-2">
                            @csrf
                            <div class="mb-2">
                                <select name="distributor_id" class="form-select" required>
                                    <option value="">Select Distributor</option>
                                    @foreach(\App\Models\User::where('is_admin', false)->get() as $user)
                                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary w-100">Assign Code</button>
                        </form>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection